export const APP_TAB_BAR_HEIGHT = 60;
export const APP_TAB_BAR_BOTTOM_GAP = 14;
export const APP_TAB_BAR_CONTENT_GAP = 20;

export const APP_TAB_BAR_CONTENT_INSET =
  APP_TAB_BAR_HEIGHT + APP_TAB_BAR_BOTTOM_GAP + APP_TAB_BAR_CONTENT_GAP;
